#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iCDR.FhirApi
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="iCDR")]
	public partial class iCDRDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public iCDRDataContext() : 
				base(global::iCDR.FhirApi.Properties.Settings.Default.iCDRConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public iCDRDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public iCDRDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public iCDRDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public iCDRDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CreateFhirResourceId")]
		public int CreateFhirResourceId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ResourceType", DbType="VarChar(50)")] string resourceType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ResourceId", DbType="Int")] ref System.Nullable<int> resourceId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), resourceType, resourceId);
			resourceId = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CreateFhirResourceVersion")]
		public int CreateFhirResourceVersion([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ResourceId", DbType="Int")] System.Nullable<int> resourceId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Version", DbType="Int")] System.Nullable<int> version, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DateTimeCreated", DbType="DateTime")] System.Nullable<System.DateTime> dateTimeCreated, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ResourceXml", DbType="Xml")] System.Xml.Linq.XElement resourceXml)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), resourceId, version, dateTimeCreated, resourceXml);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CreatePatientIdentifierResourceLink")]
		public int CreatePatientIdentifierResourceLink([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdentifierValue", DbType="VarChar(50)")] string identifierValue, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdentifierSystem", DbType="VarChar(50)")] string identifierSystem, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ResourceId", DbType="Int")] System.Nullable<int> resourceId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), identifierValue, identifierSystem, resourceId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AddToSearchIndex")]
		public int AddToSearchIndex([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ResourceId", DbType="Int")] System.Nullable<int> resourceId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Field", DbType="VarChar(50)")] string field, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Value", DbType="VarChar(100)")] string value)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), resourceId, field, value);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetFhirResourceCurrentVersion")]
		public int GetFhirResourceCurrentVersion([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ResourceId", DbType="Int")] System.Nullable<int> resourceId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ResourceVersion", DbType="Int")] ref System.Nullable<int> resourceVersion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), resourceId, resourceVersion);
			resourceVersion = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ClearSearchIndex")]
		public int ClearSearchIndex([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ResourceId", DbType="Int")] System.Nullable<int> resourceId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), resourceId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.prStoreResource")]
		public ISingleResult<prStoreResourceResult> prStoreResource([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Xml")] System.Xml.Linq.XElement resourceXml, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string resourceJSON, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string action, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string url)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), resourceXml, resourceJSON, action, url);
			return ((ISingleResult<prStoreResourceResult>)(result.ReturnValue));
		}
	}
	
	public partial class prStoreResourceResult
	{
		
		private System.DateTime _Column1;
		
		public prStoreResourceResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="DateTime NOT NULL")]
		public System.DateTime Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
